import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { ClerkProvider } from "@clerk/nextjs";
import Notification from "./(store)/components/Notification";
import Footer from "./(store)/components/Footer";
import Header from "./(store)/components/Header";
import Topbar from "./(store)/components/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen">
          <ClerkProvider>
            <Notification />
            <Header />
            <Topbar />
            <div className="bg-grey-1 h-full">{children}</div>
            <Footer />
          </ClerkProvider>
        </div>
      </body>
    </html>
  );
}
